version: "3.3"
services:
    frontend:
        image: noteme-front
        # network_mode: host
        ports:
            - 80:80
        # networks:
        #     - mynet
    backend:
        image: noteme:latest
        # network_mode: host
        ports:
            - 8080:8080
        # net: host
        # networks:
        #     - mynet
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
networks:
    default:
        external:
            name: mynet2
